### ISSUE TITLE
Absolute OutputPath breaks build

### ISSUE THREAD

**Issue by curdincaspar** [jsakamoto/nupkg-selenium-webdriver-chromedriver#14]
I build my projects with an absolute OutputPath to another directory. The "ChromeDriverTargetPath" variable thus looks like this:

`C:\ng\tests\Web.Integration.Test\C:\ng\deployment\testchromedriver.exe`

Wouldn't the $(OutputPath) as variable be enough?

**Comment by jsakamoto** [comment]
I guess, you are using v.2.21.0.0 or lower version of Selenium.WebDriver.ChromeDriver package.

Since v.2.21.0.1, the package was changed the method that how to deployment driver file to output path.

If you so. I recommend upgrade your  Selenium.WebDriver.ChromeDriver package to latest version.

I hope this operation fix your trouble.

**Comment by jsakamoto** [comment]
Oh, sorry, I can replay the error.

![image](https://cloud.githubusercontent.com/assets/95908/17537757/2bc91156-5eda-11e6-8dae-67576ccc27b5.png)

I'll try to resolve this issue.

**Comment by jsakamoto** [comment]
My Visual Studio 2015 Update 3 translate output path from absolute to relative automatically if project path and output path are in same drive.

It is the reason that I can't replay the error at first.

**Comment by jsakamoto** [comment]
I fixed it at commit dca56c8bff664e00885539ee34febd4451c2ed8d

and NuGet package was updated.
https://www.nuget.org/packages/Selenium.WebDriver.ChromeDriver

Please check out latest version of this package.
thanks.

**Comment by curdincaspar** [comment]
Hi,

Sorry for having to wait so long.
I had to switch to an older version of chrome because of some problems so I can't verify it at the moment. But the fix looks good to me!
