### ISSUE TITLE
ChromeDriver binary isn't copied on publish from Visual Studio

### ISSUE THREAD

**Issue by extstopcodepls** [jsakamoto/nupkg-selenium-webdriver-chromedriver#19]
When I publish my project (Web in my case) to file system then chromedriver.exe isn't copied to bin folder. In old solution (2.20) it was. 

When I build project then chromedriver.exe is in my bin folder as expected.

**Comment by jsakamoto** [comment]
It is by design at this time, because I think there are no needs that published files should contain webdriver executable file. (I think, "chromedriver.exe is needed at only testing time, not deployment time.")

But if you want, I'm going to resolve this issue.  

Please let me a few days or weeks.

**Comment by yayiekim** [comment]
We need that.. thanks!

**Comment by extstopcodepls** [comment]
We use chromedriver with selenium in our production app so it would be nice if chromedriver.exe will be copied to publish.

Thank you for spending your time on that,

**Comment by jsakamoto** [comment]
@extstopcodepls @yayiekim Could you try to v.2.25.0.8-beta?

https://www.nuget.org/packages/Selenium.WebDriver.ChromeDriver/2.25.0.8-beta

```
Install-Package Selenium.WebDriver.ChromeDriver -Pre
```

And, after define "_PUBLISH_CHROMEDRIVER" compilation symbol, when you publish the project, "chromedriver.exe" is included in published files.

![image](https://cloud.githubusercontent.com/assets/95908/19826561/d11d960e-9dc8-11e6-92f4-11dd5facaa79.png)

I hope this feature works fine.

**Comment by jsakamoto** [comment]
I updated "README".

https://github.com/jsakamoto/nupkg-selenium-webdriver-chromedriver/tree/improve/support-publishing#how-to-include-the-driver-file-into-published-files--ドライバーを発行ファイルに含めるには

**Comment by extstopcodepls** [comment]
Ok, I tried v.2.25.0.8-beta. I updated from v.2.25.0.0 and everything is working. Conditional compilation symbol and MSBuild file version copies chrome driver to publish package. Thank you.

**Comment by jsakamoto** [comment]
@extstopcodepls Thank you for your reply.

I released it as official version (not beta).
https://www.nuget.org/packages/Selenium.WebDriver.ChromeDriver/2.25.0.8
