### ISSUE TITLE
chromedriver.exe not copied when using PackageReference

### ISSUE THREAD

**Issue by mscrivo** [jsakamoto/nupkg-selenium-webdriver-chromedriver#22]
To get the chromedriver.exe copied to your output folder when using PackageReference instead of packages.config, you need to use <contentFiles> in your .nuspec.  See here: https://docs.microsoft.com/en-us/nuget/schema/nuspec#including-content-files

**Comment by jsakamoto** [comment]
I tried to reproduce the problem, but I could not.

My test drive application is a .NET Core 2.0 console application, and my development environment is Visual Studio 2017 Update 3 (15.3.5) on Windows 10 x64 Pro.

![image](https://user-images.githubusercontent.com/95908/31605077-4051807a-b2a0-11e7-810f-c70342a7a182.png)

My project's source code is here: [TestDriveNETCore20.zip](https://github.com/jsakamoto/nupkg-selenium-webdriver-chromedriver/files/1386865/TestDriveNETCore20.zip)

Could you please explain more details to reproduce the problem on my environment?

**Comment by mscrivo** [comment]
hmm, I'm seeing the same thing as you now.  We had a bunch of projects that used packages.config and when I updated them to use PackageReferences, I noticed the exe was not getting copied over, not sure what the difference is now.

**Comment by jsakamoto** [comment]
Is there possibility about the bug of Visual Studio related with reloading project files?

Anyway, I'm considering to cancel pull request from you at this time.

If you have more opinions, please let me know feel free :)

**Comment by mscrivo** [comment]
yeah that's fine with me.  Thanks for taking a look!
