### ISSUE TITLE
ChromeDriver 2.38 causes browser crashes in Chrome 66 when running parallel tests

### ISSUE THREAD

**Issue by tajyoder** [jsakamoto/nupkg-selenium-webdriver-chromedriver#26]
Hello! 

Current version of ChromeDriver packaged in this project is ChromeDriver 2.38.551581. Per issue reported at https://bugs.chromium.org/p/chromedriver/issues/detail?id=2391&can=2&q=2391&colspec=ID%20Status%20Pri%20Owner%20Summary, this version contains a bug that will cause Chrome browsers to crash when running multiple tests in parallel in newer versions of Chrome, including newly-released Chrome 66. 

Updated ChromeDriver 2.38.552522 (released 4/21) resolves this issue. Could the new version of 2.38 please be included in this package? Thanks!

**Comment by jsakamoto** [comment]
Thank you for your reporting! 👍 

I could not know that patched version was released, if you do not tell me as this issue.

I released new package v.2.38.0.1.

https://www.nuget.org/packages/Selenium.WebDriver.ChromeDriver/2.38.0.1

Thanks!

**Comment by tajyoder** [comment]
Tested and verified that package v2.38.0.1 resolves this issue. Thank you very much for the update!
