### ISSUE TITLE
Can't seem to download compressed sources

### ISSUE THREAD

**Issue by benfranklin79** [jsakamoto/nupkg-selenium-webdriver-chromedriver#28]
I just tried to the following url:

https://github.com/jsakamoto/nupkg-selenium-webdriver-chromedriver/releases/tag/v.2.38.0.1

and tried both compressed downloads and got a 404 not found in both cases

**Comment by jsakamoto** [comment]
I tried do that just now, but it worked fine.

![image](https://user-images.githubusercontent.com/95908/44532879-27edd680-a72f-11e8-82b4-70555ee22848.png)

The problem is not responsible for me, it should be treated by GitHub, I think.

Could you try to contact to GitHub support?
