### ISSUE TITLE
 Cannot start the driver service on http://localhost

### ISSUE THREAD

**Issue by ThatoMolefe** [jsakamoto/nupkg-selenium-webdriver-chromedriver#30]
I would kindly like to ask for help an issue I have running selenium on on a windows server without an interface, I get the following error: Cannot start the driver service on http://localhost:49906/    at OpenQA.Selenium.DriverService.Start()    at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)    at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)    at OpenQA.Selenium.Rem

**Comment by jsakamoto** [comment]
Please give me more and more details information about your problem, like the following post:

https://github.com/jsakamoto/nupkg-selenium-webdriver-chromedriver/issues/29#issuecomment-420610220

- OS type, edition, version ...
- .NET Framework? or .NET Core? or Mono? And what version is that?
- What version is Google Chrome, Selenium WebDriver, and ChromeDriver?
etc.

Your post is too less information, therefore I can't do anything to resolve your problem. 😢 

If you can provide all of the source code that to reproduce the problem on my machine to me, it is very very helpful for me.

**Comment by jsakamoto** [comment]
Since there is no responses, I'll close this issue.

If anybody still have same problem, feel free to reopen this issue.
