### ISSUE TITLE
.NET core console project publish does not include chromedriver.exe in publish directory

### ISSUE THREAD

**Issue by k290** [jsakamoto/nupkg-selenium-webdriver-chromedriver#32]
Good day,

If I have a .NET Core 2 Console Application, I can successfully get chromedriver.exe in the bin directory.
However, if I publish it as a standalone application (so that I can later include it in a .msi) I do not get chromedriver.exe in the bin\Debug\netcoreapp2.0\publish directory.

Steps to reproduce:
1. Right click Console application project. Click publish. Then click the "publish" menu item on the left. Select a Folder Profile to publish the application to a directory on disk.
2. Click configure.  Set deployment mode to "self-contained". This will result in a .exe output for the Console app. Set target runtime to win-x86, (for publishing for a Windows machine)
3. Click publish.
4.  bin\Debug\netcoreapp2.0\publish has all output files except chromedriver.exe

Please advise.

**Comment by jsakamoto** [comment]
Did you try to define `_PUBLISH_CHROMEDRIVER` compilation symbol to active configuratiol ("Debug" or "Release")?

![fig.1](https://github.com/jsakamoto/nupkg-selenium-webdriver-chromedriver/raw/master/.asset/define_PUBLISH_CHROMEDRIVER_compilation_symbol.png)

See also: https://github.com/jsakamoto/nupkg-selenium-webdriver-chromedriver#how-to-include-the-driver-file-into-published-files--%E3%83%89%E3%83%A9%E3%82%A4%E3%83%90%E3%83%BC%E3%82%92%E7%99%BA%E8%A1%8C%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%AB%E5%90%AB%E3%82%81%E3%82%8B%E3%81%AB%E3%81%AF

In my case, I tried it on .NET Core 2.0 console app just now, it was successful.

![image](https://user-images.githubusercontent.com/95908/46580580-6d0d6400-ca62-11e8-8451-7b4b808c390b.png)

All of my sample code is here: [TestDriveNETCore20.zip](https://github.com/jsakamoto/nupkg-selenium-webdriver-chromedriver/files/2453792/TestDriveNETCore20.zip)

P.S. By the way, I found another bug of this NuGet package that this package always publish win32 driver when profile is macOS of linux OS.

**Comment by k290** [comment]
That works. Thank you.
