### ISSUE TITLE
This package always publish win32 driver when profile is macOS of linux OS (not windows OS).

### ISSUE THREAD

**Issue by jsakamoto** [jsakamoto/nupkg-selenium-webdriver-chromedriver#33]

**Comment by arnolddg** [comment]
FYI, I had a similar problem, where the fix appears to be a change in Selenium.WebDriver.ChromeDriver.targets, by surrounding the first few property groups (up to the first Target) in a new target (let's call it "DetectOsPlarform") and setting the InitialTargets attribute of the Project to "DetectOsPlarform"

**Comment by jsakamoto** [comment]
commit #9f1cdee1c7a6eae47a7f9eca15b2ca6f8a6c1618 will fix this,
