### ISSUE TITLE
IWebElement GetAttribute method not working as expected

### ISSUE THREAD

**Issue by adrian109** [jsakamoto/nupkg-selenium-webdriver-chromedriver#35]
Hi,

I don't seem to be able to get the class attribute values from the below HTML:

`<img class="seat i-a lvl_9f978e18-59e7-460c-a9dd-025d792c90c1 c" alt="D/203" src="style/images/hall/a.png" id="chair_56" style="left: 259.735px; top: 536.648px; width: 16.6928px; height: 16.6928px; transform: rotate(180.07deg);" data-realrowindex="3" data-realcolindex="21" data-seatinfo="null">`

I can find the <img> element by its id and get a valid IWebElement object, however when I call:
```
var element = ExplicitWait.Until(ExpectedConditions.ElementIsVisible(By.Id("chair_56")));
var classValues = element?.GetAttribute("class");
```

**Expected result:**
variable _classValues_ holds the value: "seat i-a lvl_9f978e18-59e7-460c-a9dd-025d792c90c1 c"

**Actual result:**
variable _classValues_ holds the value: "System.Object[]"

**Comment by adrian109** [comment]
Hi,

I have downloaded your test project, run it and it works as expected.

However if I change the url to the page I'm using it fails:
```
driver.Navigate().GoToUrl("https://www.seagullstickets.com/en-GB/events/albion%20v%20arsenal/2018-12-26_17.15/american%20express%20community%20stadium?area=c5eae2e3-b424-4010-94cb-11c22d0a54e3&type=");
```
Can you try using the url I'm using to see if it works for you.

Thanks.

**Comment by jsakamoto** [comment]
I could reproduce this issue.

However, I have no idea that why this behavior was caused.

Unfortunately, I'm not developer of Selenium, Selenium WebDriver, I'm just building package only.

Therefore, you should post this issue to stackoverflow.com, or contact somebody who is developer of Chrome WebDriver.
