### ISSUE TITLE
Debug is removing chromedriver.exe from ~\bin\debug\.

### ISSUE THREAD

**Issue by LorneCash** [jsakamoto/nupkg-selenium-webdriver-chromedriver#36]
This may be a visual studio issue but I'm curious if anyone else is having this same problem and since I'm not sure I'm posting it here.  When I rebuild chromedriver.exe is created in my ~\bin\debug folder as expected.  Then I try to start debugging and I can see chromedriver.exe disappear right as the WinForm UI appears on my screen.  In my case my WinForm project is not the one with the PackageReference to ChromeDriver but rather it's in a referenced .NET Framework (4.7.2) Class Library project with the compilation symbols set to '_PUBLISH_CHROMEDRIVER'.

Again though my problem isn't that it's not copying if I stop debugging and rebuild it get's coppied back to the ~\bin\debug folder but as soon as I  start Debugging it's deleted again.  So like I said I'm guessing this is some quirk with Visual Studio but I wanted to post here just in case.

I did find a workaround that's working so far... after rebuilding I browse to ~\bin\debug\ and set chromedriver.exe as readonly.  I thought that if others are having this same problem maybe this solution could be added to the nuget project so no one else has this problem unless of course being readonly would cause some other problem I'm not aware of.

**Comment by jsakamoto** [comment]
Close due to no response.
