### ISSUE TITLE
ChromeDriver naming convention change

### ISSUE THREAD

**Issue by SeanKilleen** [jsakamoto/nupkg-selenium-webdriver-chromedriver#38]
On the [ChromeDriver download page](http://chromedriver.chromium.org/downloads) and the [version selection page](http://chromedriver.chromium.org/downloads/version-selection), Chrome has decided to use a naming schema that coincides with the major chrome versions. 

So, going forward, there will not be versions like `2.46` that map to multiple versions of chrome; there will instead of be a semver-compatible version released that maps to the actual browser versions.

Are there any plans to shift to the same convention as the official chrome driver releases?

**Comment by jsakamoto** [comment]
Thank you for notifying me! 👍 

I'll shift to the same convention as the official chrome driver release as soon as possible.

Please wait for publishing new version of the NuGet packages.

**Comment by SeanKilleen** [comment]
Oh cool, thanks! That's a lot of work (since you have to monitor multiple URLs for version updates, etc.) -- I appreciate you maintaining this as it's a big help to our team. 👍 

FYI I reached out to the ChromeDriver mailing list to see if they have any way of subscribing to these published versions. I figured that way we could at least automate some of the process and save some time. Will let you know if I hear anything back.

**Comment by nsleigh** [comment]
But this changes the way it works - if you want a driver for the release version this code will update to the beta version. It feels to me that there should be two versions of this code, one for release one for beta - or something like that.

**Comment by SeanKilleen** [comment]
@nsleigh my understanding is this would not be beta but rather the released drivers that correspond to a major/minor version of chrome. So they should still be stable I believe.

**Comment by nsleigh** [comment]
> If you are using Chrome version 73, please download ChromeDriver 73.0.3683.20
> If you are using Chrome version 72, please download ChromeDriver 2.46 or ChromeDriver 72.0.3626.69
So it you update now don't you get 73.0.3683.20 which means it only supports Chrome 73 - it might work with 72 but that is not the point.

**Comment by SeanKilleen** [comment]
I see -- the concern is mostly that folks upgrading to the latest might lose some compatibility? My understanding is that it currently works this way given that driver versions still map to sets of chrome browser compatibility. 

Sorry if I'm missing something. Can you highlight an example of how this would be fundamentally different than the current package consumer experience?

**Comment by nsleigh** [comment]
If I read it correctly, instead of supporting a range of versions the driver is now specific to a version of chrome. In my case I test v-next with chrome beta (v73) and v-current with chrome (v72) and I was updating to the latest chrome driver (2.46). Now I need one driver for v72 and another for v73.

Unless I am missing something!

**Comment by jsakamoto** [comment]
Folks upgrading to the latest might lose some compatibility, I think too.

> Now I need one driver for v72 and another for v73.

Maybe it is correct.

It is limitation of this NuGet package that this package can't resolve @nsleigh 's problem, at this time.

I think, to resolve it, we should find another solution, like https://github.com/bonigarcia/webdrivermanager on Java platform. 

( I have some plan to create .NET porting of https://github.com/bonigarcia/webdrivermanager, but I have no time! )

**Comment by nsleigh** [comment]
I would suggest it is better that this package supports the live version, that is what most people would need. I you want to test with the beta then you would have manually get the newer version.

**Comment by jsakamoto** [comment]
@nsleigh Would You like to say "You (@jsakamoto)  should not have published this NuGet package of ChromeDriver v73 at this time, because the Chrome v73 is still beta." ?

Yes, I agree that may be correct.

I could publish v73 of this NuGet package with the "-beta" suffix, at this time.

I'll do this next chance.

**Comment by SeanKilleen** [comment]
@jsakamoto @nsleigh that makes sense to me in general 👍 

One point that's worth mentioning -- it sounds like they are mapping the ChromeDriver not just to a major version but to a `major`.`minor`.`build` version -- from the [Version selection guide](http://chromedriver.chromium.org/downloads/version-selection):

> Each version of ChromeDriver supports Chrome with matching major, minor, and build version numbers. For example, ChromeDriver 73.0.3683.20 supports all Chrome versions that start with 73.0.3683.

So for every major/minor/patch of chrome, there could be multiple ChromeDrivers available. For each _build_ of chrome, you'd have to go to:

`http://chromedriver.storage.googleapis.com/LATEST_RELEASE_[MajorMinorBuild]` (Example, I'm on `72.0.3626` so I'd need to go to http://chromedriver.storage.googleapis.com/LATEST_RELEASE_72.0.3626)

It then gives you the version of ChromeDriver to use with that version of Chrome -- in this case `72.0.3626.69`. I think this is the driver we'd need to provide.

The challenges seem to be:

* There will be many different Chrome builds. Deciding which to support could be problematic.
* Even after you publish versions for a build, you need to check back in case there are bugfixes. 
* There doesn't seem to be an easy way to subscribe to all the released versions of ChromeDriver, so you're bound to miss some versions.

**Comment by SeanKilleen** [comment]
Oh I see -- actually it looks like you would at least have the option to support the latest for each major version by using a URL for that major version, e.g. http://chromedriver.storage.googleapis.com/LATEST_RELEASE_72 would give you the latest release, `72.0.3626.69`, which you could then publish.

That's at least less to monitor for changes.

However, because they'll be back-porting bug fixes, etc. you may need to monitor all major versions for update.

I bet we could automate this if you're interested::

* We could probably build a small serverless component that opens a github issue every time these version numbers increase for a major number 
* We could build a bot that takes this requests and creates a package for publishing & a release.

Could be a fun little project. 😄

**Comment by SeanKilleen** [comment]
Jackpot! I just realized that there's an XML doc at the base URL that has every published version: http://chromedriver.storage.googleapis.com/

**Comment by jsakamoto** [comment]
I'm already watching newer version release automatically by Azure Functions + C#.

https://github.com/jsakamoto/WebDriverUpdateDetector

This implementation only try to detect most latest version, but it can change to detect multiple versions easily, therefore I'll do that changes ;)

**Comment by SeanKilleen** [comment]
@jsakamoto nice! :) that's awesome.
