### ISSUE TITLE
Clipboard not working in headless mode

### ISSUE THREAD

**Issue by arora12** [jsakamoto/nupkg-selenium-webdriver-chromedriver#40]
The following method works perfectly in the normal mode but when used in the headless mode it doesn't work at all for some reason

writingBox.SendKeys(OpenQA.Selenium.Keys.Control + 'v');

I'm using this method to speed up the typing process of a long piece of text
I've tried implementing a direct Javascript method to input stuff in but on the website I'm trying to get this to work, unless it sees a key press event or a copy paste event it doesn't let me change the text on a particular field

Any way to get the Clipboard paste working in the headless mode?

**Comment by arora12** [comment]
:(

**Comment by richja** [comment]
Have the same issue and after some googling, it seems like this is a limitation of headless mode.

**Comment by jsakamoto** [comment]
> Have the same issue and after some googling, it seems like this is a limitation of headless mode.

Thanks for your report, @richja .

I'll close this issue due to it may be specification and limitation of chrome or chromedriver.

**Comment by Mtsumi** [comment]
Anyone found a solution for this?
