### ISSUE TITLE
session not created: This version of ChromeDriver only supports Chrome version 74   (Driver info: chromedriver=74.0.3729.6)

### ISSUE THREAD

**Issue by VictorioBerra** [jsakamoto/nupkg-selenium-webdriver-chromedriver#43]
```
lass Initialization method MyProject.MyProjectTestPlan.SetUp threw exception. System.InvalidOperationException: System.InvalidOperationException: session not created: This version of ChromeDriver only supports Chrome version 74
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.14393 x86_64) (SessionNotCreated).
```

My Packages.Config

 ```
 <package id="Selenium.Support" version="3.141.0" targetFramework="net461" />
  <package id="Selenium.WebDriver" version="3.141.0" targetFramework="net461" />
  <package id="Selenium.WebDriver.ChromeDriver" version="74.0.3729.6" targetFramework="net461" />
```

Is `74 !== 74.0.3729.6` ???

**Comment by AnnemarieD** [comment]
👍 

I am having a similar issue, but then with this version of Chromedriver I get the error:
```System.InvalidOperationException : session not created: Chrome version must be between 70 and 73
  (Driver info: chromedriver=2.45.615355 (d5698f682d8b2742017df6c81e0bd8e6a3063189),platform=Mac OS X 10.14.4 x86_64) (SessionNotCreated)```

My Packages:
```    <PackageReference Include="Selenium.Support" Version="3.141.0" />
    <PackageReference Include="Selenium.WebDriver" Version="3.141.0" />
    <PackageReference Include="Selenium.WebDriver.ChromeDriver" Version="74.0.3729.6" />
```

**Comment by SubjectiveReality** [comment]
It would be really cool if this nuget package also included the chrome version that pairs with the chromedriver version, and copies chrome.exe (and dependencies) to bin/debug/chrome (for example) from packages in a manner similar to how chromedriver.exe is copied.

**Comment by nipuns11** [comment]
Kind of the same thing for me Message: System.InvalidOperationException : session not created: This version of ChromeDriver only supports Chrome version 76 (SessionNotCreated)
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.
I downloaded the latest chrome driver 78.0.3904.7000 and my chrome browser version is 78.0.3904.97, I killed all chrome driver processes /cleaned solution but still, somehow it shows version 76

**Comment by devhl-labs** [comment]
I had this issue.  I got around it by specifying where the proper driver was located.

**Comment by jsakamoto** [comment]
Is the workaround that specify the path to directory of chromedriver which you want to use resolve this issue?

like this:

```csharp
using (var driver = new ChromeDriver("path to directory of chromedriver which you want to use"))
{
   ...
```

**Comment by devhl-labs** [comment]
Yes.  I think the only thing this nuget does is drop the exe in our bin for
us, so this issue basically makes the nuget useless for now.  I removed it
from my aplication.
