### ISSUE TITLE
linux binary is not present in bin folder for version 74

### ISSUE THREAD

**Issue by stoyankolev** [jsakamoto/nupkg-selenium-webdriver-chromedriver#44]
When using chrome driver version 74 on linux machine, only chromedriver.exe is copied to the bin folder, but not the linux binary. The restore and build is done with "dotnet build" command.

**Comment by jsakamoto** [comment]
Would you try to `dotnet build -p:WebDriverPlatform=linux64` ?

Please see also ["Cross platform building and publishing - Method 2 - Specify "WebDriverPlatform" msbuild property" section of latest README](https://github.com/jsakamoto/nupkg-selenium-webdriver-chromedriver#method-2---specify-webdriverplatform-msbuild-property)

**Comment by stoyankolev** [comment]
We made another implementation and this question is no longer relevant to us. I will close it and I hope your answer can be helpful to others.
