### ISSUE TITLE
driver.Manage().Logs.GetLog(LogType.Browser) throws NullReference exception

### ISSUE THREAD

**Issue by alex-jitbit** [jsakamoto/nupkg-selenium-webdriver-chromedriver#45]
See the subj. Getting the console log throws an exception now

**Comment by alex-jitbit** [comment]
This might be related to https://github.com/SeleniumHQ/selenium/issues/7323 so it *might* be irrelevant

**Comment by sureshready** [comment]
driver.Manage().Logs.GetLog(LogType.Browser) throws NullReference exception, . Any news about the release date of this fix? we still face same issue...

**Comment by aliquid** [comment]
Hitting the same, running ChromeDriver 80.0.3987.16.

Workaround is downgrading to Selenium v3.7.0 (problems start with v3.8.0).
