### ISSUE TITLE
ChromeDriver 76.0.3809.68 released!

### ISSUE THREAD

**Issue by mide1234** [jsakamoto/nupkg-selenium-webdriver-chromedriver#46]
Hey, a new major version of ChromeDriver was released. Would you mind updating your package?
https://chromedriver.chromium.org/

Thanks a lot

**Comment by rjl5201** [comment]
@jsakamoto I am also looking for this package to be updated. Thank you!

**Comment by jsakamoto** [comment]
Anybody always can install latest version of Chrome Driver from a pre-release packages like following command.

```powershell
PM> Install-Package Selenium.WebDriver.ChromeDriver -Version 76.0.3809.68-beta -IncludePrerelease
```

Anyway, I'll re-package Chrome Driver v.76 as an official release.

Thanks for the heads-up me!

**Comment by mide1234** [comment]
Thanks for the package!

I believe it is not allowed to consume unstable (pre-release packages) in a stable product. You would need to mark your product as unstable as well which is often NOT what you want/can do.

**Comment by jsakamoto** [comment]
I released v76 as an official package.

https://www.nuget.org/packages/Selenium.WebDriver.ChromeDriver/76.0.3809.68

**Comment by mide1234** [comment]
Yeah, thanks a lot for that.
