### ISSUE TITLE
should add to bin the os targed chrome driver

### ISSUE THREAD

**Issue by lastlink** [jsakamoto/nupkg-selenium-webdriver-chromedriver#48]
when on windows I run ` dotnet publish -c Release -r osx.10.12-x64` or `dotnet build -r osx.10.12-x64` I see `chromedriver.exe` for windows rather than the `chromedriver` for mac.

**Comment by jsakamoto** [comment]
Would you try to ver.76.0.3809.68**01** ?

https://www.nuget.org/packages/Selenium.WebDriver.ChromeDriver/76.0.3809.6801

For more detail of this release, please see also ["Cross platform building and publishing" section of  README.](https://github.com/jsakamoto/nupkg-selenium-webdriver-chromedriver#cross-platform-building-and-publishing)

**Comment by lastlink** [comment]
great thanks!
