### ISSUE TITLE
Can't access browser console log since v75

### ISSUE THREAD

**Issue by igor-teresco** [jsakamoto/nupkg-selenium-webdriver-chromedriver#50]
Have Selenium test which is reading browser console log for any errors like this:
ChromeOptions c_opt = new ChromeOptions();
c_opt.SetLoggingPreference(LogType.Browser, LogLevel.All);
driver = new ChromeDriver(c_opt);
consoleLogs = driver.Manage().Logs.GetLog(LogType.Browser);

Until v75 it was working as expected, since that version I'm getting System.NullReferenceException.
Am I doing something wrong or that capability was removed?

**Comment by Lemadd** [comment]
I think this is related to https://github.com/SeleniumHQ/selenium/issues/7323 , unfortunately, that will part of selenium 4, which is currently in alpha version.

**Comment by orifn1** [comment]
I have the same issue, problem is: 
`AvailableLogTypes = '((OpenQA.Selenium.Remote.RemoteLogs)webDriverlogs).AvailableLogTypes' threw an exception of type 'System.NullReferenceException'`
![image](https://user-images.githubusercontent.com/6146067/66396522-97319300-e9e2-11e9-82b8-5e332eb0e1af.png)

**Comment by jsakamoto** [comment]
Duplicate https://github.com/jsakamoto/nupkg-selenium-webdriver-chromedriver/issues/45

**Comment by orifn1** [comment]
why do you close this issue?
