### ISSUE TITLE
chmod being executed on windows platform

### ISSUE THREAD

**Issue by stlinsley** [jsakamoto/nupkg-selenium-webdriver-chromedriver#51]
Using the last few versions of the chromedriver package, we have noticed that whenever we install the latest update (or reinstall all packages), that the build in Visual Studio fails with the error:
_The command "chmod +x""" exited with code 9009._

We tracked this down to the following being called:

2>Using "Exec" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
2>Task "Exec" (TaskId:15)
2>  Task Parameter:Command=chmod +x "" (TaskId:15)
2>  chmod +x "" (TaskId:15)
2>  'chmod' is not recognized as an internal or external command, (TaskId:15)
2>  operable program or batch file. (TaskId:15)

Obviously being on Windows the chmod command won't work. The only workaround we have is to close VS and reopen it, and then it works okay for that person.

**Comment by LasseHifi** [comment]
It may also help to clean (delete all files) the build folder but most of the time restarting VS is ok.

**Comment by stlinsley** [comment]
Tried clean and build, clean and rebuild, restarting visual studio is the only solution currently. It's not ideal for everyone in the team to have to restart VS everytime, especially when it shouldn't be happening anyway.

**Comment by jsakamoto** [comment]
Would you try to ver.76.0.3809.68**01** ?

https://www.nuget.org/packages/Selenium.WebDriver.ChromeDriver/76.0.3809.6801

It includes following patch.

[https://github.com/jsakamoto/nupkg-selenium-webdriver-chromedriver/commit/9f1cdee1c7a6eae47a7f9eca15b2ca6f8a6c1618#diff-87eb6b0f4cc7a7e3bdd3ae3b40f6ba25R23](https://github.com/jsakamoto/nupkg-selenium-webdriver-chromedriver/commit/9f1cdee1c7a6eae47a7f9eca15b2ca6f8a6c1618#diff-87eb6b0f4cc7a7e3bdd3ae3b40f6ba25R23)

**Comment by stlinsley** [comment]
Yep, this resolved it. Cheers!
