### ISSUE TITLE
problem to use version 77.0.3865.4000-beta

### ISSUE THREAD

**Issue by amir124** [jsakamoto/nupkg-selenium-webdriver-chromedriver#52]
bellow error appear when run the program :
: 'session not created: This version of ChromeDriver only supports Chrome version 77 (SessionNotCreated)

my options driver:
            options = new ChromeOptions();
            options.AddArgument("headless");
            options.AddArgument(@"user-data-dir=C:\Users\ghgfhfgh\AppData\Local\Google\Chrome\User Data\Profile");  
            options.AddArgument("enable-automation");
            options.AddArgument("start-maximized");
            options.AddArgument("disable-infobars");
            //options.AddArgument("disable-application-cache");
            //options.AddArgument("disk-cache-size=0");
            options.AddArguments("no-sandbox");
            options.AddArguments("ignore-certificate-errors");
            options.AddArguments("test-type");
            options.AddArgument("off-screen-rendering-enabled");
            options.AddArgument("disable-accelerated-compositing");
            options.AddArgument("disable-extensions");
            options.AddArgument("disable-plugins-discovery");
            options.AddArgument("disable-bundled-ppapi-flash");
            options.AddArgument("disable-popup-blocking");
            options.AddArgument("--no-sandbox");
            //options.AddArgument("--disable-local-storage");
            //options.AddArgument("disable-local-storage");
            options.AddArgument("disable-default-apps");
            options.AddArgument("ignore-gpu-blacklist");
            options.AddArgument("no-default-browser-check");
            options.AddArgument("disable-plugins");
            options.AddArgument("blink-settings=imagesEnabled=false");
            options.AddArguments("disable-notifications", "disable-accelerated-video", "disable-plugins-discovery", "disable-javascript", "disabled", "no-network-profile-warning", "disable-renderer-backgrounding", "disable-background-timer-throttling", "disable-background-networking", "disable-javascript-harmony-shipping", "disable-translate");
            options.PageLoadStrategy = PageLoadStrategy.None;
            options.AddUserProfilePreference("profile.default_content_setting_values.automatic_downloads", 1);
            options.SetLoggingPreference(LogType.Profiler, LogLevel.Off);
            options.SetLoggingPreference(LogType.Browser, LogLevel.Off);
            options.SetLoggingPreference(LogType.Client, LogLevel.Off);
            options.SetLoggingPreference(LogType.Driver, LogLevel.Off);
            options.SetLoggingPreference(LogType.Server, LogLevel.Off);
            options.SetLoggingPreference("performance", LogLevel.Off);
            options.Proxy = null;
            CurrentDriver = new ChromeDriver(options);

![image](https://user-images.githubusercontent.com/5613106/63491336-297de600-c4cc-11e9-9111-860a91991441.png)

**Comment by jsakamoto** [comment]
It's contradictory.

The title of this issue said "**v.77**.0.3865.4000-beta", but the screen shot above said that you are using "**v.76**.0.3809.6801".

Which information is correct?

**Comment by amir124** [comment]
oh  i'm sorry this screen shot is wrong
this is my screen shot  :
![Untitlaaed](https://user-images.githubusercontent.com/5613106/63514929-fe60ba00-c4fe-11e9-9a48-7e40a1cd8c66.png)


26/5000
How to fix this problem?

**Comment by jsakamoto** [comment]
What is the version of the Google Chrome Web Browser (chrome.exe) in your environment?

![image](https://user-images.githubusercontent.com/95908/63515212-3e3a9800-c525-11e9-8ad6-c4800d6515b5.png)

**Comment by amir124** [comment]
![Untitddddled](https://user-images.githubusercontent.com/5613106/63515373-fb19fe00-c4ff-11e9-9be7-511a22e32c4d.jpg)

**Comment by jsakamoto** [comment]
You have to keep the versions of Google Chrome Web Browser and Chrome WebDriver to same major version.

In this case, you should use v.76.x package.

- https://www.nuget.org/packages/Selenium.WebDriver.ChromeDriver/76.0.3809.12600

Please see also the article bellow.

- https://chromedriver.chromium.org/downloads/version-selection

**Comment by amir124** [comment]
Thank you
