### ISSUE TITLE
ChromeDriver 76.0.3809.126 released

### ISSUE THREAD

**Issue by EdwinVanVliet** [jsakamoto/nupkg-selenium-webdriver-chromedriver#53]
Hi,

Is there support coming for this version of ChromeDriver?
It has been released on 2019-08-20.

With kind regards,
Edwin

**Comment by jsakamoto** [comment]
Thank you for your report!

I published the package of ChromeDriver 76.0.3809.126 released, just now.

**Comment by EdwinVanVliet** [comment]
Thanks for the fast support.
