### ISSUE TITLE
Issue with Chromedriver 78.0.3904.70 and chrome 78

### ISSUE THREAD

**Issue by lucas937** [jsakamoto/nupkg-selenium-webdriver-chromedriver#61]
Since ive upgraded the chromedriver to the latest version 78.0.3904.70 and also chrome to Version 78.0.3904.70 (Official Build) (64-bit). I keep getting unable to locate elements.. 

Message: OpenQA.Selenium.NoSuchElementException : no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='CountrySelection']/tbody/tr[2]/td[3]/div/table/tbody/tr/td[2]/a[9]"}
  (Session info: chrome=78.0.3904.70)

Error Message: session not created: This version of ChromeDriver only supports Chrome version 76 (SessionNotCreated)
Stack Trace:    at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeOptions options)
   at XylectSeleniumTest.Selenium.Driver.Driver.driverChrome() in C:\Users\fasx937\source\repos\XylectRegression\XylectSeleniumTest\Selenium\Driver\Driver.cs:line 40
   at XylectSeleniumTest.BaseSetUp.Setup() in C:\Users\fasx937\source\repos\XylectRegression\XylectSeleniumTest\BaseSetUp\BaseSetUp.cs:line 75
Inner Exception: 

I havent changed the code since the 77 version of chromedriver and chrome,,

**Comment by jsakamoto** [comment]
According to this error message,

> Error Message: session not created: This version of ChromeDriver only supports Chrome version 76 (SessionNotCreated)

the build result of your project would be something wrong, I think.

Could you check the output folder  (ex: "~/bin/Debug/netcore3.0") and could you find the chromedriver binary file is there?

If you find it, could you execute it?

If you execute chromedriver binary directly, it will report the version number itself.

If the version number doesn't v.78, please delete all files in the output folder and rebuild your project.

**Comment by lucas937** [comment]
Thanks for the reply! 
> If you find it, could you execute it?
> If you execute chromedriver binary directly, it will report the version number itself.
Yes, version 78 was shown. 
> If the version number doesn't v.78, please delete all files in the output folder and rebuild your project.
Did this, did not help however.. 

problem is that i haven't changed my solution since i updated to chrome & chromedriver 78.. ever since this i've gotten problems. below is the error message i get. Also when i debug the testcase and step through it works, so i guess its something with the Wait function that's not working 

![image](https://user-images.githubusercontent.com/48093059/67670152-92be2180-f973-11e9-8b0f-862aafc6e0ab.png)

**Comment by lucas937** [comment]
Case can be closed.. Found an issue in the Page Object classes where i get the chromedriver to find the elements. I wasnt getting the chromedriver that was initialized on setup.. 

My question is why this worked with all previous versions on chrome and chromedriver... 

Old setup
public AllProjectsPage(IWebDriver _driver) => driver = _driver;

New setup 
public AllProjectsPage(IWebDriver driver)
        {
            this.driver = driver;
            ChromeOptions options = new ChromeOptions();
            options.AddArgument("disable-infobars");
            driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);
            SeleniumExtras.PageObjects.PageFactory.InitElements(driver, this);
        }
