### ISSUE TITLE
Question: clarify version numbering

### ISSUE THREAD

**Issue by jawn** [jsakamoto/nupkg-selenium-webdriver-chromedriver#62]
From the release history, I see that the nuget version used to be the same as the chrome driver version number.

Since NuGet version **77.0.3865.4000** for chromedriver version **77.0.3865.40**, the revision part is multiplied by 100. 

Is this intentional?
If yes, can we trust that this will stay the same?

78.0.3904.7000
- Chrome Driver 78.0.3904.70 release
 78.0.3904.1100
- Chrome Driver 78.0.3904.11 release
77.0.3865.4000
- Chrome Driver 77.0.3865.40 release
77.0.3865.10
- Chrome Driver 77.0.3865.10 release

Motivation: 

We may consider to automatically determine the nuget version to use just before running selenium tests, based on the Chrome version.

First we'ld follow these instuctions
https://chromedriver.chromium.org/downloads/version-selection

Then we'ld convert the current chromedriver version to the corresponding nuget version.
Then install the nuget.

**Comment by jsakamoto** [comment]
> Is this intentional?

Yes, it is.

>  can we trust that this will stay the same?

Yes, you can.

Sometimes, I have to update the version number of this package to publish a fixed version that something troubles of build script in this package.

In this scenario, I have to change the version number of the package, however, the version number of Chrome Driver uses all of the part (major, minor, build patch) of version semantics.

Therefore, I came up with the idea of the version numbering of this package, like this:

chromedriver version MAJOR.MINOR.BUILD.PATCH + package version (2 digit)

See also:
https://github.com/jsakamoto/nupkg-selenium-webdriver-chromedriver#the-numbering-of-the-package-version
