### ISSUE TITLE
session not created from tab crashed chrome=78.0.3904.70

### ISSUE THREAD

**Issue by DamianRdz** [jsakamoto/nupkg-selenium-webdriver-chromedriver#64]
session not created from tab crashed  (Session info: chrome=78.0.3904.70) (SessionNotCreated)'
This happen with .Net Core 2.2 when we run a new driver with Chrome 78.0.3904.70 the driver with the same version shows the  'session not created from tab crashed  (Session info: chrome=78.0.3904.70) (SessionNotCreated)'

**Comment by nipuns11** [comment]
Kind of the same thing for em Message: System.InvalidOperationException : session not created: This version of ChromeDriver only supports Chrome version 76 (SessionNotCreated)
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.

**Comment by DamianRdz** [comment]
> Kind of the same thing for me Message: System.InvalidOperationException : session not created: This version of ChromeDriver only supports Chrome version 76 (SessionNotCreated)
> TearDown : System.NullReferenceException : Object reference not set to an instance of an object.
> I downloaded the latest chrome driver 78.0.3904.7000 and my chrome browser version is 78.0.3904.97

we found with the team, it was an issue in our side with the antivirus (Windows machine)

**Comment by jsakamoto** [comment]
To @DamianRdz:

Was this issue resolved? Can I close this issue?

To @nipuns11:

Is the workaround that specify the path to directory of chromedriver which you want to use resolve this issue?

like this:

```csharp
using (var driver = new ChromeDriver("path to directory of chromedriver which you want to use"))
{
   ...
```

**Comment by DamianRdz** [comment]
> To @DamianRdz:
> 
> Was this issue resolved? Can I close this issue?
> 
> To @nipuns11:
> 
> Is the workaround that specify the path to directory of chromedriver which you want to use resolve this issue?
> 
> like this:
> 
> ```cs
> using (var driver = new ChromeDriver("path to directory of chromedriver which you want to use"))
> {
>    ...
> ```

from my side, yes, you can close it
