### ISSUE TITLE
Support different Chrome versions in different environments

### ISSUE THREAD

**Issue by guybeauchamp** [jsakamoto/nupkg-selenium-webdriver-chromedriver#67]
Is it possible to support different versions of Chrome in different environments? My dev environment is two Chrome versions ahead of the test environment, so which version of chromedriver do I install? Can chromedriver be backwards-compatible?

**Comment by jsakamoto** [comment]
> Is it possible to support different versions of Chrome in different environments?

Unfortunately, this NuGet package doesn't support installing different versions of chromedriver in a project.

> Can chromedriver be backward-compatible?

I'm not sure about backward compatibility of chromedriver.

How about the "WebDriverManager.Net"?

https://github.com/rosolko/WebDriverManager.Net

I've never used "WebDriverManager.Net", but it seems like a good solution for you.

**Comment by guybeauchamp** [comment]
That looks like it will work. I'll try it and let you know.
Many thanks!
