### ISSUE TITLE
The driver is not copied to the bin folder on a VM

### ISSUE THREAD

**Issue by Jonathan--V** [jsakamoto/nupkg-selenium-webdriver-chromedriver#71]
I have added this package to my project through NuGet, producing the following line in packages.config:

  <package id="Selenium.WebDriver.ChromeDriver" version="81.0.4044.6900" targetFramework="net472" />

If I build my solution (or just one project) on my pc, everything behaves as expected - the driver is downloaded to `\packages\Selenium.WebDriver.ChromeDriver.81.0.4044.6900\driver\win32` and subsequently copied into the binary folder: `\bin\x64\Debug`. I have experienced no problems with this package on my machine for the 6+ months I've been using it.

However, when I run the exact same code on a vm (AWS-hosted, running Windows Server 2016 Datacenter), I experience a strange issue: on build, the driver is downloaded to `\packages\Selenium.WebDriver.ChromeDriver.81.0.4044.6900\driver\win32` (correct, as before) but it is NOT then copied to `\bin\x64\Debug` as part of the build process. This then leads my Selenium tests to fail as it cannot find the ChromeDriver. The exception is thrown on the line:

`ChromeDriverService chromeDriverService = ChromeDriverService.CreateDefaultService();`

and the exception has the message:

`OpenQA.Selenium.DriverServiceNotFoundException: 'The chromedriver.exe file does not exist in the current directory or in a directory on the PATH environment variable. The driver can be downloaded at http://chromedriver.storage.googleapis.com/index.html.'`

One of my colleagues seems to experience no issues (same as me locally). Another colleague seems to have similar issues running on a different VM.

Possibly relevant information:
c#: 8
Selenium WebDriver: 3.141.0

I am also experiencing the same issue with your Geckodriver and IEDriver NuGetPackages: they work fine on my PC, but they don't copy to Debug on the VM.

Please let me know if any more information might be helpful.

What might be causing this behaviour? Is there any way I might be able to resolve it?

**Comment by jsakamoto** [comment]
@Jonathan--V 

Could you provide the project file to me that you can reproduce this issue on a Windows Server 2016 datacenter AWS hosted VM?

**Comment by Jonathan--V** [comment]
Thanks for looking into this. 

I attach the csproj file copied from the VM. I have changed the extension to .txt (as required by GitHub's file uploading feature). I have removed the listings of files and other projects, as indicated in comments. The file is otherwise unchanged.

[Project Name.txt](https://github.com/jsakamoto/nupkg-selenium-webdriver-chromedriver/files/4661753/Project.Name.txt)

Please let me know if there is anything else that would help.

**Comment by jsakamoto** [comment]
@Jonathan--V Thank you for your help.

I could reproduce the issue.

I'll try to fix this problem.

The workaround at this time is, please try to reopen and rebuild the project after close it once on Visual Studio.

**Comment by jsakamoto** [comment]
@Jonathan--V 

I published the new version of this package.

- https://www.nuget.org/packages/Selenium.WebDriver.ChromeDriver/83.0.4103.3910-beta

(It is Beta release.)

Could you try it out?

**Comment by Jonathan--V** [comment]
I have tried performing the same steps with both the old and the new version and the new version correctly copies the Chromedriver across into the binaries folder.

Thank you very much for resolving this. 

Might you be able to perform similar changes for the Geckodriver and IEDriver packages?

**Comment by jsakamoto** [comment]
Thanks for your report!

> Might you be able to perform similar changes for the Geckodriver and IE Driver packages?

All right.

I published the new version of GeckoDriver to fix the same issue on that package.

- https://www.nuget.org/packages/Selenium.WebDriver.GeckoDriver/0.26.0.3-beta

I'm still working on fixing the issue of IEDriver. I'm so busy, so please give me more few days.

**Comment by jsakamoto** [comment]
@Jonathan--V 

I also published the new version of IEDriver.

- https://www.nuget.org/packages/Selenium.WebDriver.IEDriver/3.150.1.1-beta#

Could you try it out?

**Comment by Jonathan--V** [comment]
I have tried the new packages for GeckoDriver and IEDriver. With both, the driver is copied to the binaries folder on the VM.

Thank you very much for resolving these too.

**Comment by jsakamoto** [comment]
@Jonathan--V 

Thank you for your report!

Many people will be rescued from this trouble by your report :)
