### ISSUE TITLE
Plans to update to v83?

### ISSUE THREAD

**Issue by jbcrowley** [jsakamoto/nupkg-selenium-webdriver-chromedriver#72]
Chromedriver v83 has been out for a few weeks now and the current version of the driver no longer works with Chrome v83. When do you plan to update the package to v83 of Chromedriver? Thanks.

**Comment by shirishnagarnz** [comment]
Waiting for ChromeDriver v83 eagerly. Thanks.

**Comment by jsakamoto** [comment]
Anybody always can install latest version of Chrome Driver from a pre-release packages like following command.

PM> Install-Package Selenium.WebDriver.ChromeDriver -Version {version}-beta -IncludePrerelease

Anyway, I re-packaged Chrome Driver v.83 as an official release.

- https://www.nuget.org/packages/Selenium.WebDriver.ChromeDriver/83.0.4103.3900

Thanks for the heads-up me!
