### ISSUE TITLE
Cannot restore package Selenium.WebDriver.ChromeDriver.83.0.4103.3900

### ISSUE THREAD

**Issue by adamsow** [jsakamoto/nupkg-selenium-webdriver-chromedriver#74]
Hi,
I have an issue in TFS that this package can't be restored:

PackageSignatureVerificationLog: PackageIdentity: Selenium.WebDriver.ChromeDriver.83.0.4103.3900 Source: https://api.nuget.org/v3/index.json PackageSignatureValidity: False
WARNING: Unable to find version '83.0.4103.3900' of package 'Selenium.WebDriver.ChromeDriver'.
'Selenium.WebDriver.ChromeDriver.83.0.4103.3900' is not found on source 
  https://api.nuget.org/v3/index.json: 

Do you have any idea what may be the issue here? Especially why PackageSignatureValidity is false?

Thanks,
Adam

**Comment by jsakamoto** [comment]
Unfortunately, I have no idea, but the error messages are very similar to the issue below.

https://github.com/NuGet/Home/issues/8011

Will that is helpful for you?

**Comment by adamsow** [comment]
It was something wrong with NuGet version 5.x, changing it to version 4.x solved the problem.

Thanks,
Adam

**Comment by jsakamoto** [comment]
I am happy you resolved your problem :)
