### ISSUE TITLE
ChromeDriver 87.0.4280.88 released

### ISSUE THREAD

**Issue by WKenya** [jsakamoto/nupkg-selenium-webdriver-chromedriver#80]
Hello,

A new release of ChromeDriver v87.0.4280.88 was just made that fixed some issues I was experiencing.

**Comment by jsakamoto** [comment]
@WKenya Thank you for notify me!

I published a new package just now.

- https://www.nuget.org/packages/Selenium.WebDriver.ChromeDriver/87.0.4280.8800

Thanks!

**Comment by WKenya** [comment]
Thank you!
