### ISSUE TITLE
Update for 91.0.4472.114

### ISSUE THREAD

**Issue by Jetski5822** [jsakamoto/nupkg-selenium-webdriver-chromedriver#82]
It seems Chrome has a blanket update that has stopped selenium working;

Could we get an update for 91.0.4472.114 please.

 OpenQA.Selenium.WebDriverException : unknown error: unable to discover open window in chrome
      (Session info: chrome=91.0.4472.114)

Cheers, Nick

**Comment by jsakamoto** [comment]
The combination that Google Chrome v.91.0.4472.**114** and Selenium ChromeDriver v.91.0.4472.**101** worked fine on my PC.

![image](https://user-images.githubusercontent.com/95908/123402676-f2eee600-d5e2-11eb-8549-f04d7c673b2b.png)

and it looks there are no v.91.0.4472.**114** version of Selenium ChromeDriver at this time.

- https://chromedriver.storage.googleapis.com/LATEST_RELEASE_91

What can I do?

**Comment by Jetski5822** [comment]
Weird - I just ran locally and it seems fine. But on other people laptops its not working. I think its safe to close this, must be environmental.

Thanks for looking - N
