### ISSUE TITLE
Update to ChromeDriver 94

### ISSUE THREAD

**Issue by eddiegieze** [jsakamoto/nupkg-selenium-webdriver-chromedriver#83]
Hi,

ChromeDriver 94 has been released. Could you release a new version of the NuGet for version 94?

https://chromedriver.storage.googleapis.com/index.html?path=94.0.4606.41/

Thanks!

**Comment by jsakamoto** [comment]
Thanks for letting me know! 👍

I published the ChromeDriver NuGet package for v.94 just now.

- https://www.nuget.org/packages/Selenium.WebDriver.ChromeDriver/94.0.4606.4101-beta

Please try it out! 😊

**Comment by eddiegieze** [comment]
Thanks a lot!
