### ISSUE TITLE
Support Arm64 Versions of ChromeDriver for M1

### ISSUE THREAD

**Issue by bjharo** [jsakamoto/nupkg-selenium-webdriver-chromedriver#91]
Would it be possible to get support for the Arm64 builds of chromedriver that support Apple M1 processors? Currently, I do my test development on a Macbook with a M1. When I include this package in my project and build, the Mac x64 version of the driver is downloaded. Technically, it does work because I have Rosetta enabled but tests run slower. 

Currently, Chrome on Mac is a universal binary that has both the x64 and arm64 builds in it. If an x64 version of chromedriver starts Chrome, it will start the x64 version of Chrome rather than the arm64 version. This is due to how Rosetta handles spawning child processes. If a x64 process starts a child process and that process is a universal app, then Rosetta will use the same architecture of the parent process. Because both chromedriver and Chrome are running in x64 mode, tests are running a fair bit slower.

**Comment by LarsThunberg** [comment]
@bjharo This is not a question/Issue for this project. Please see the Selenium main page: [https://www.selenium.dev/](https://www.selenium.dev/ )

**Comment by jsakamoto** [comment]
Thanks to everyone for your contributions!

Actually, I found the mac64 **M1** binary of ChromeDriver on the download site.

- https://chromedriver.storage.googleapis.com/index.html?path=102.0.5005.61/

![image](https://user-images.githubusercontent.com/95908/170698358-5a195a35-84d2-43c9-ad87-2688bff511bc.png)

So I'll include the binary file of the M1 version of the ChromneDriver into this NuGet package.

Please wait for a while.

**Comment by bjharo** [comment]
@jsakamoto Thanks!

**Comment by jsakamoto** [comment]
@bjharo  I published the new version of the "Selenium.WebDriver.ChromeDriver" NuGet package that contains the Chrome Driver binary for Apple M1. 🎉

- https://www.nuget.org/packages/Selenium.WebDriver.ChromeDriver/102.0.5005.6101

![image](https://user-images.githubusercontent.com/95908/170812651-cc153849-ee0e-4df7-9b46-f16982bd3f92.png)

Could you try it out?

**Comment by bjharo** [comment]
@jsakamoto Just tried it out. It works great.  Thanks!

**Comment by jsakamoto** [comment]
@bjharo Thank you for your trying out and your contributions!
