### ISSUE TITLE
Chromedriver for mac64arm not copied to target output for mac M1 visual studio build.  

### ISSUE THREAD

**Issue by NateKokuno** [jsakamoto/nupkg-selenium-webdriver-chromedriver#95]
Nuget installing Selenium.WebDriver.ChromeDriver.111.0.5563.6400 on mac m1. From the build log, I don't see the copy of chrome driver over to the target output.  (bin/Debug)

Target ChmodChromeDriver: chmod +x "/Users/.../packages/Selenium.WebDriver.ChromeDriver.111.0.5563.6400/build/../driver/mac64/chromedriver" Target ChmodGeckoDriver: chmod +x "/Users/.../packages/Selenium.WebDriver.GeckoDriver.0.32.2/build/../driver/mac64/geckodriver" Target ChmodMsEdgeDriver: chmod +x "/Users/.../packages/Selenium.WebDriver.MSEdgeDriver.110.0.1587.50/build/../driver/mac64/msedgedriver"

I didn't see the target of chrome driver getting copied:

Target CopyGeckoDriverToBin: Copying file from "/Users/...packages/Selenium.WebDriver.GeckoDriver.0.32.2/driver/mac64/geckodriver" to "/Users/.../bin/Debug/geckodriver". Target CopyMsEdgeDriverToBin: Copying file from "/Users/d...packages/Selenium.WebDriver.MSEdgeDriver.110.0.1587.50/driver/mac64/msedgedriver" to "/Users/.../bin/Debug/msedgedriver". sourcefiles: /Users/.../packages/Selenium.WebDriver.MSEdgeDriver.110.0.1587.50/build/../driver/mac64/msedgedriver destinationfiles: /Users/.../bin/Debug/msedgedriver

I tried setting RID to osx-mac64 in .cproj file under PropertyGroup, but Edge driver side complained build failed with exit code. I guess edge doesn't understand that RID tag and threw a build error.  Removed that line and geckodriver and msedgedriver did get copied over.  Just that Chromedriver isn't.  

Can you tell me what went wrong for Mac M1 build? thanks.

**Comment by NateKokuno** [comment]
Thanks @jsakamoto for your quick response.  I think the fact that my project was originally from a windows VS2019 project and I git pulled it into VS mac and needed to remove 2 lines like the  <ProjectTypeGuids> and <VisualStudioVersion> and the project runs, but it cannot debug because it doesn't stop at a break point.  I recreate a local vs mac nunit tests and it works with the chromedriver dropping in the output folder.  Thank you for your help.  I took it for granted that the visual studio older projects will work across platforms and obviously not.  I'm on mac OS Ventura.  New nunit test project from scratch:  
![image](https://user-images.githubusercontent.com/99159769/225831621-dcd543d4-5519-4007-8f21-bce8d970d847.png)

Now I am pondering if I should find a way to "convert" that VS2019 nunit test to work with VS mac, or create a native vs mac test and drop files over as a new project.  Anyways, thanks!

**Comment by jsakamoto** [comment]
@NateKokuno Thank you for your reply! So, I'll close this issue. But of course, please don't hesitate re-open this issue if you need it.
