### ISSUE TITLE
Part URI cannot start with two forward slashes / 406 errors when pushing to nuget server

### ISSUE THREAD

**Issue by fhanggi** [jsakamoto/nupkg-selenium-webdriver-chromedriver#98]
Hello
I cannot upload this nuget package to my nuget server.
i keep getting 406 errors and also see this error
w3wp.exe Error: 0 : System.ArgumentException: Part URI cannot start with two forward slashes.

I nailed it down to this line inside [Content_Types].xml

<Override PartName="//LICENSE" ContentType="application/octet" />

Is there a chance you can remove one of these forward slashes?

Thank you very much.
Fabian

**Comment by jsakamoto** [comment]
Thank you for letting me know that, @fhanggi !

I released the fixed version right now (follow the link below).

- https://www.nuget.org/packages/Selenium.WebDriver.ChromeDriver/122.0.6261.6901

Could you check it out?
Thanks!

**Comment by fhanggi** [comment]
Wow what a response time. 

It is now working. Thank you so much . Saves me a ton of work.
